### PR TITLE
Update to `jupyterlite-core==0.1.0b22`

### PR DESCRIPTION
**Pull request by jtpio**
Update to the latest release: https://github.com/jupyterlite/jupyterlite/releases/tag/v0.1.0b20

- [x] Update to `jupyterlite-core==0.1.0b22`
- [x] Disabling `@jupyterlite/javascript-kernel-extension` is not needed anymore

### CODE REVIEW

**Review by bollwyvl — APPROVED** [review]
Seems like the right play, and will help make this repo's demo/test surface area smaller.

**Comment by jtpio** [comment]
ah looks like it might be because `jupyterlite-core==0.1.0b20` does not include the following two fixtures:

- the-smallest-extension-0.1.0-py_0.tar.bz2
- the_smallest_extension-0.1.0-py3-none-any.whl

I guess we could add them back upstream although the upstream tests don't need them to pass apparently.

**Comment by jtpio** [comment]
Looks like the tests in this repo should actually make use of the fixture available in https://github.com/jupyterlite/pyodide-kernel/blob/main/jupyterlite_pyodide_kernel/tests/fixtures/the_smallest_extension-0.1.0-py3-none-any.whl

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlite/pyodide-kernel/pull/39

**Pull request closed without merging**
