### PR TITLE
Update to Pyodide 0.23.0a1

### PR DESCRIPTION
**Pull request by jtpio**
Port of https://github.com/jupyterlite/jupyterlite/pull/962

image

### CODE REVIEW

**Comment by bollwyvl** [comment]
while i'm pro getting up to this, as it bumps to a new python major and a new micropip strategy, figure we'll want something we can stand behind on 3.10 before punching too hard on this.

**Comment by jtpio** [comment]
Opening this mostly to get the demo on the RTD, and so we can close https://github.com/jupyterlite/jupyterlite/pull/962.

**Comment by bollwyvl** [comment]
https://github.com/pyodide/pyodide/releases/tag/0.23.0

Will take a look at revving this, see what we can do with the [micropip updates](https://github.com/pyodide/micropip/blob/main/CHANGELOG.md#030---20230329).

**Comment by chrysn** [comment]
[0.23.0 has been released](https://github.com/pyodide/pyodide/releases/tag/0.23.0), so it may make sense to re-target this effort.

I've looked through the changes since 0.23.0a1 (which is most easily done with `git log --patch 0.23.0a1..0.23.0 docs/project/changelog.md` comparing tags, because the changelog as such was changed), but as far as I can tell from an outsider's perspective, the changes shouldn't make this PR harder; here's a summary grouping the changes how I think is useful for here:

* the addition of py-compiled builds (might interfere with `>>> object??`, not sure if used by default),
* removal of things deprecated since v0.22.0
* isPyProxy became stricter in presence of multiple interpreters
* AUTO_JS_LIBRARIES and AUTO_NATIVE_LIBRARIES disabled
* deprecations that can be fixed throughout the v0.23 cycle
* bundling: pyodid_py.tar is now part of python_stdlib.zip
* upstream package updates (eg. micropip 0.3.0) and additions
* API additions
* added features to the build process
* documentation and testing changes

**Comment by jtpio** [comment]
Fixed by https://github.com/jupyterlite/pyodide-kernel/pull/39

**Pull request closed without merging**
