### PR TITLE
Add the Pyodide kernel from the JupyterLite repository

### PR DESCRIPTION
**Pull request by jtpio**
Import the Pyodide kernel from https://github.com/jupyterlite/jupyterlite while trying to keep most of the history.

Corresponding PR on the JupyterLite repo: https://github.com/jupyterlite/jupyterlite/pull/854

Partially following https://docs.github.com/en/get-started/using-git/splitting-a-subfolder-out-into-a-new-repository:

```bash
# fresh clone of the jupyterlite repo into a temporary folder
git clone https://github.com/jupyterlite/jupyterlite tmp-pyodide-kernel
cd tmp-pyodide-kernel

# install git-filter-repo: https://github.com/newren/git-filter-repo/blob/main/INSTALL.md
# filter the two directories
python ~/git/git-filter-repo --path packages/pyolite-kernel --path packages/pyolite-kernel-extension

# go back to the jupyterlite-pyodide-kernel repo (this one)
git remote add import ../tmp-pyodide-kernel
git merge import/main --allow-unrelated-histories

# delete tmp-pyodide-kernel (not needed anymore)
```

This only grabs the changes that were made to the following folder and will omit changes done outside (webpack config, README, dodo, examples):
- `packages/pyolite-kernel`
- `packages/pyolite-kernel-extension`

### TODO

- [x] Bring pyolite packages with the history
- [x] Rename to `pyodide-kernel` and `pyodide-kernel-extension`
- [x] Keep the base and `-extension` packages for now. We might reconsider later whether there should be only one package to keep things simple (to be discussed)
- [x] incorporate changes from PRs that were merged since the beginning of the split:
  - [x] https://github.com/jupyterlite/jupyterlite/pull/899 (needs `0.1.0b16+` to grab the `IServiceWorkerManager` rename)
  - [x] https://github.com/jupyterlite/jupyterlite/pull/911
  - [x] https://github.com/jupyterlite/jupyterlite/pull/900
  - [x] https://github.com/jupyterlite/jupyterlite/pull/913
- [x] re-add scripts and logic from dodo as plain scripts if possible (will try to not add doit to keep things simple unless very necessary). Look into using the lerna / nx declarative task pipeline: https://lerna.js.org/docs/concepts/task-pipeline-configuration
- [x] add the CLI addon: https://github.com/jupyterlite/jupyterlite/blob/c4360950ff7341107f7f3b4ec0502b99485254d8/py/jupyterlite/src/jupyterlite/addons/pyodide.py
- [x] Fix versioning and releaser hooks
- [x] Fix shared webpack modules not available in the web worker
- [x] handle Pyodide specific config. This seems to be working when testing with `disablePyPIFallback` (https://jupyterlite.readthedocs.io/en/latest/reference/schema-v0.html#pyolite-settings):

image

- [x] Reset version to `0.0.1` to prepare for the releaser
- [x] Fix bumping of `piplite` and `pyodide_kernel` in `package.json`
- [x] Add the Python tests

### CODE REVIEW

**Comment by jtpio** [comment]
Kicking CI.

**Comment by jtpio** [comment]
Will probably start over to grab the latest changes that landed in https://github.com/jupyterlite/jupyterlite.

Add add the latest commits on top of it.

**Comment by bollwyvl** [comment]
Is there some workflow that would reduce the effort needed on this? maybe a short-lived submodule? or is manually merging easier?

**Comment by jtpio** [comment]
It would probably be fine to do it like in this PR by grabbing the commits from the jupyterlite repo, to release the kernel as a federated kernel first.

And then merge the [corresponding PR](https://github.com/jupyterlite/jupyterlite/pull/854) on the jupyterlite repo shortly after, followed by a release.

**Comment by jtpio** [comment]
OK I will probably stop here for now and check the Python tests in a separate PR, since they need quite a bit of setup to work (install jupyterlite from https://github.com/jupyterlite/jupyterlite/pull/854).

The kernel seems to work fine when using the jupyterlite wheel built by the released in https://github.com/jupyterlite/jupyterlite/pull/854:

image

**Follow-ups**

- Publish a first `jupyterlite-pyodide-kernel` 0.0.x for testing
- Add it to https://github.com/jupyterlite/jupyterlite/pull/854
- Finish https://github.com/jupyterlite/jupyterlite/pull/854
- Check how to include `jupyterlite-pyodide-kernel` in `jupyterlite` by default for now
- More testing to make sure indexing wheels and other features specific to the pyodide kernel still work fine

**Pull request merged**
